sudo: required
dist: trusty
notifications:
  email: false
language: python
cache: pip
python:
  - "3.5.2"
addons:
  - postgresql: '9.5.14'
env:
  - DJANGO_SETTINGS_MODULE=iamsitting_site.settings.travis DJANGO_VERSION=2.1.5
install:
  - pip install -r requirements/test.txt
  - npm install
before_script:
  - psql -c 'create database iamsitting_site;' -U postgres
  - python iamsitting_site/manage.py makemigrations
script:
  - python iamsitting_site/manage.py migrate --noinput
  - npm run build
after_success:
  - sh scripts/test_suite.sh

