version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - node-modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
 postgres_data:
 node-modules:

